version: "3.7"

services:

  products-db:
    # docker exec -it products-db mongosh -u mongodb -p mongodb products-db/development
    container_name: products-db
    build:
      context: .
      dockerfile: Dockerfile.database
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=development
      - MONGO_NON_ROOT_USERNAME=mongodb
      - MONGO_NON_ROOT_PASSWORD=mongodb
    volumes:
      # Persist data that is stored in db after
      # container is shutdown.
      - product-db_data:/data/db
    networks:
      - product-api-net
    command: mongod --quiet --logpath /dev/null
    # ports:
    #   - 27017:27017
  
  products-api-develop:
    hostname: products-api-develop
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_DB_HOST=products-db
    depends_on:
      - products-db
    # https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy
    restart: unless-stopped
    networks:
      - product-api-net
    # ports:
    #   - "9000:9000"

  nginx-service:
    container_name: nginx-service
    build:
      context: nginx
      dockerfile: Dockerfile.develop
    restart: unless-stopped
    networks:
      - product-api-net
    ports:
      - "80:80"
    depends_on:
      - products-api-develop
 

volumes:
  product-db_data:

networks:
  product-api-net: