import os
BACKEND_CORS_ORIGINS = 1

API_PREFIX = "/v1"

MONGO_NON_ROOT_USERNAME = "mongodb"
MONGO_NON_ROOT_PWD = "mongodb"
MONGO_INITDB_DATABASE = "development"
MONGO_HOST = os.getenv("MONGO_HOST", "products-db")
MONGODB_URL  = f"mongodb://{MONGO_NON_ROOT_USERNAME}:{MONGO_NON_ROOT_PWD}@{MONGO_HOST}:27017/{MONGO_INITDB_DATABASE}"